"""Create initial data models

Revision ID: 99f831f97024
Revises: 
Create Date: 2025-09-28 19:06:51.134832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f831f97024'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('pdf_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('field_count', sa.Integer(), nullable=True),
    sa.Column('sepe_url', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_pdf_templates_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_templates'))
    )
    op.create_index(op.f('ix_pdf_templates_created_at'), 'pdf_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_pdf_templates_id'), 'pdf_templates', ['id'], unique=False)
    op.create_index(op.f('ix_pdf_templates_name'), 'pdf_templates', ['name'], unique=False)
    op.create_index(op.f('ix_pdf_templates_version'), 'pdf_templates', ['version'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_template_id', sa.Integer(), nullable=False),
    sa.Column('target_template_id', sa.Integer(), nullable=False),
    sa.Column('comparison_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('differences_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_comparisons_created_by_users')),
    sa.ForeignKeyConstraint(['source_template_id'], ['pdf_templates.id'], name=op.f('fk_comparisons_source_template_id_pdf_templates')),
    sa.ForeignKeyConstraint(['target_template_id'], ['pdf_templates.id'], name=op.f('fk_comparisons_target_template_id_pdf_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparisons'))
    )
    op.create_index(op.f('ix_comparisons_created_at'), 'comparisons', ['created_at'], unique=False)
    op.create_index(op.f('ix_comparisons_id'), 'comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_comparisons_source_template_id'), 'comparisons', ['source_template_id'], unique=False)
    op.create_index(op.f('ix_comparisons_status'), 'comparisons', ['status'], unique=False)
    op.create_index(op.f('ix_comparisons_target_template_id'), 'comparisons', ['target_template_id'], unique=False)
    op.create_table('template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['pdf_templates.id'], name=op.f('fk_template_versions_template_id_pdf_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_versions'))
    )
    op.create_index(op.f('ix_template_versions_id'), 'template_versions', ['id'], unique=False)
    op.create_index(op.f('ix_template_versions_is_current'), 'template_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    op.create_table('comparison_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], name=op.f('fk_comparison_fields_comparison_id_comparisons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparison_fields'))
    )
    op.create_index(op.f('ix_comparison_fields_change_type'), 'comparison_fields', ['change_type'], unique=False)
    op.create_index(op.f('ix_comparison_fields_comparison_id'), 'comparison_fields', ['comparison_id'], unique=False)
    op.create_index(op.f('ix_comparison_fields_id'), 'comparison_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_fields_id'), table_name='comparison_fields')
    op.drop_index(op.f('ix_comparison_fields_comparison_id'), table_name='comparison_fields')
    op.drop_index(op.f('ix_comparison_fields_change_type'), table_name='comparison_fields')
    op.drop_table('comparison_fields')
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_is_current'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_comparisons_target_template_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_status'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_source_template_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_created_at'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_pdf_templates_version'), table_name='pdf_templates')
    op.drop_index(op.f('ix_pdf_templates_name'), table_name='pdf_templates')
    op.drop_index(op.f('ix_pdf_templates_id'), table_name='pdf_templates')
    op.drop_index(op.f('ix_pdf_templates_created_at'), table_name='pdf_templates')
    op.drop_table('pdf_templates')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
