"""add_activity_table

Revision ID: db8d42b28869
Revises: 20251027_110000
Create Date: 2025-11-02 10:49:53.307626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db8d42b28869'
down_revision: Union[str, None] = '20251027_110000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create activity table for audit trail
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    # Create indexes for performance
    op.create_index(op.f('ix_activity_activity_type'), 'activity', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_entity_id'), 'activity', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_index(op.f('ix_activity_timestamp'), 'activity', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_timestamp'), table_name='activity')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_entity_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_activity_type'), table_name='activity')
    # Drop activity table
    op.drop_table('activity')
    # ### end Alembic commands ###
