"""Add template metadata and template_fields table

Revision ID: fa338313b3a3
Revises: 99f831f97024
Create Date: 2025-10-19 12:52:24.766841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fa338313b3a3'
down_revision: Union[str, None] = '99f831f97024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'template_fields',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.Column('field_id', sa.String(length=255), nullable=False),
        sa.Column('field_type', sa.String(length=50), nullable=False),
        sa.Column('raw_type', sa.String(length=50), nullable=True),
        sa.Column('page_number', sa.Integer(), nullable=False),
        sa.Column('field_page_order', sa.Integer(), nullable=False),
        sa.Column('near_text', sa.Text(), nullable=True),
        sa.Column(
            'value_options',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True
        ),
        sa.Column(
            'position_data',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['version_id'],
            ['template_versions.id'],
            name=op.f('fk_template_fields_version_id_template_versions'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_template_fields'))
    )
    op.create_index(
        op.f('ix_template_fields_id'),
        'template_fields',
        ['id'],
        unique=False
    )
    op.create_index(
        op.f('ix_template_fields_version_id'),
        'template_fields',
        ['version_id'],
        unique=False
    )
    op.add_column(
        'template_versions',
        sa.Column('title', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'template_versions',
        sa.Column('author', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'template_versions',
        sa.Column('subject', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'template_versions',
        sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'template_versions',
        sa.Column(
            'modification_date',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )
    op.add_column(
        'template_versions',
        sa.Column(
            'page_count',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_versions', 'page_count')
    op.drop_column('template_versions', 'modification_date')
    op.drop_column('template_versions', 'creation_date')
    op.drop_column('template_versions', 'subject')
    op.drop_column('template_versions', 'author')
    op.drop_column('template_versions', 'title')
    op.drop_index(
        op.f('ix_template_fields_version_id'),
        table_name='template_fields'
    )
    op.drop_index(
        op.f('ix_template_fields_id'),
        table_name='template_fields'
    )
    op.drop_table('template_fields')
    # ### end Alembic commands ###
