"""add_cascade_delete_to_template_foreign_keys

Revision ID: fa5f5b201072
Revises: db8d42b28869
Create Date: 2025-11-08 11:30:31.980687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa5f5b201072'
down_revision: Union[str, None] = 'db8d42b28869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_comparison_fields_comparison_id_comparisons', 'comparison_fields', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comparison_fields_comparison_id_comparisons'), 'comparison_fields', 'comparisons', ['comparison_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_pdf_templates_version', table_name='pdf_templates')
    op.create_index(op.f('ix_pdf_templates_current_version'), 'pdf_templates', ['current_version'], unique=False)
    op.drop_constraint('fk_template_fields_version_id_template_versions', 'template_fields', type_='foreignkey')
    op.create_foreign_key(op.f('fk_template_fields_version_id_template_versions'), 'template_fields', 'template_versions', ['version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('template_fields', 'value_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('template_fields', 'position_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_template_versions_current_lookup', table_name='template_versions', postgresql_where='(is_current = true)')
    op.drop_index('idx_template_versions_version_number', table_name='template_versions')
    op.drop_constraint('uq_template_versions_template_id_version_number', 'template_versions', type_='unique')
    op.drop_constraint('fk_template_versions_template_id_pdf_templates', 'template_versions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_template_versions_template_id_pdf_templates'), 'template_versions', 'pdf_templates', ['template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_template_versions_template_id_pdf_templates'), 'template_versions', type_='foreignkey')
    op.create_foreign_key('fk_template_versions_template_id_pdf_templates', 'template_versions', 'pdf_templates', ['template_id'], ['id'])
    op.create_unique_constraint('uq_template_versions_template_id_version_number', 'template_versions', ['template_id', 'version_number'])
    op.create_index('idx_template_versions_version_number', 'template_versions', ['version_number'], unique=False)
    op.create_index('idx_template_versions_current_lookup', 'template_versions', ['template_id', 'is_current'], unique=False, postgresql_where='(is_current = true)')
    op.alter_column('template_fields', 'position_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('template_fields', 'value_options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_template_fields_version_id_template_versions'), 'template_fields', type_='foreignkey')
    op.create_foreign_key('fk_template_fields_version_id_template_versions', 'template_fields', 'template_versions', ['version_id'], ['id'])
    op.drop_index(op.f('ix_pdf_templates_current_version'), table_name='pdf_templates')
    op.create_index('ix_pdf_templates_version', 'pdf_templates', ['current_version'], unique=False)
    op.drop_constraint(op.f('fk_comparison_fields_comparison_id_comparisons'), 'comparison_fields', type_='foreignkey')
    op.create_foreign_key('fk_comparison_fields_comparison_id_comparisons', 'comparison_fields', 'comparisons', ['comparison_id'], ['id'])
    # ### end Alembic commands ###
