-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.comparison_fields
(
    id serial NOT NULL,
    comparison_id integer NOT NULL,
    field_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    field_type character varying(100) COLLATE pg_catalog."default",
    change_type character varying(50) COLLATE pg_catalog."default",
    old_value text COLLATE pg_catalog."default",
    new_value text COLLATE pg_catalog."default",
    position_x double precision,
    position_y double precision,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT pk_comparison_fields PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comparisons
(
    id serial NOT NULL,
    source_template_id integer NOT NULL,
    target_template_id integer NOT NULL,
    comparison_type character varying(50) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    differences_count integer,
    created_by integer,
    created_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    CONSTRAINT pk_comparisons PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pdf_templates
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    current_version character varying(50) COLLATE pg_catalog."default" NOT NULL,
    uploaded_by integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    comment text COLLATE pg_catalog."default",
    CONSTRAINT pk_pdf_templates PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.template_fields
(
    id serial NOT NULL,
    version_id integer NOT NULL,
    field_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    field_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    raw_type character varying(50) COLLATE pg_catalog."default",
    page_number integer NOT NULL,
    field_page_order integer NOT NULL,
    near_text text COLLATE pg_catalog."default",
    value_options jsonb,
    position_data jsonb,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT pk_template_fields PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.template_versions
(
    id serial NOT NULL,
    template_id integer NOT NULL,
    version_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    change_summary text COLLATE pg_catalog."default",
    is_current boolean,
    created_at timestamp with time zone DEFAULT now(),
    title character varying(255) COLLATE pg_catalog."default",
    author character varying(255) COLLATE pg_catalog."default",
    subject character varying(255) COLLATE pg_catalog."default",
    creation_date timestamp with time zone,
    modification_date timestamp with time zone,
    page_count integer NOT NULL DEFAULT 0,
    file_path character varying(500) COLLATE pg_catalog."default" NOT NULL,
    file_size_bytes integer NOT NULL,
    field_count integer NOT NULL DEFAULT 0,
    sepe_url character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT pk_template_versions PRIMARY KEY (id),
    CONSTRAINT uq_template_versions_template_id_version_number UNIQUE (template_id, version_number)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    is_superuser boolean,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.comparison_fields
    ADD CONSTRAINT fk_comparison_fields_comparison_id_comparisons FOREIGN KEY (comparison_id)
    REFERENCES public.comparisons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_comparison_fields_comparison_id
    ON public.comparison_fields(comparison_id);


ALTER TABLE IF EXISTS public.comparisons
    ADD CONSTRAINT fk_comparisons_created_by_users FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comparisons
    ADD CONSTRAINT fk_comparisons_source_template_id_pdf_templates FOREIGN KEY (source_template_id)
    REFERENCES public.pdf_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_comparisons_source_template_id
    ON public.comparisons(source_template_id);


ALTER TABLE IF EXISTS public.comparisons
    ADD CONSTRAINT fk_comparisons_target_template_id_pdf_templates FOREIGN KEY (target_template_id)
    REFERENCES public.pdf_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_comparisons_target_template_id
    ON public.comparisons(target_template_id);


ALTER TABLE IF EXISTS public.pdf_templates
    ADD CONSTRAINT fk_pdf_templates_uploaded_by_users FOREIGN KEY (uploaded_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.template_fields
    ADD CONSTRAINT fk_template_fields_version_id_template_versions FOREIGN KEY (version_id)
    REFERENCES public.template_versions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_template_fields_version_id
    ON public.template_fields(version_id);


ALTER TABLE IF EXISTS public.template_versions
    ADD CONSTRAINT fk_template_versions_template_id_pdf_templates FOREIGN KEY (template_id)
    REFERENCES public.pdf_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_template_versions_template_id
    ON public.template_versions(template_id);

END;